# Generated by Django 4.2.17 on 2024-12-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название графы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='up_images/')),
                ('main_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Картинка верхней части',
                'verbose_name_plural': 'Картинки верхней части',
            },
        ),
    ]
